services:
  docker-dynolog:
    container_name: dynolog
    command: --use_prometheus true
    build:
      context: ./
      target: docker_dynolog
      args:
        - USE_PROMETHEUS=ON
    volumes:
      - /proc:/proc





